[project]
channels = [ "https://brainvisa.info/neuro-forge", "nvidia", "pytorch", "conda-forge",]
description = "Add a short description here"
name = "brainvisa"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = [ "activate.sh",]

[dependencies]
cmake = "*"
gcc = "*"
git = "*"
gxx = "*"
libglu = "*"
libglvnd-devel-cos7-x86_64 = "*"
libstdcxx-devel_linux-64 = "*"
make = "*"
mesa-libgl-devel-cos7-x86_64 = "*"
mesalib-devel-only = "*"
pip = "*"
pyaml = "*"
pytest = "*"
rattler-build = ">=0.13"
six = "*"
sphinx = "*"
toml = "*"
virtualgl = "*"
pydicom = "*"
xlrd = "*"
xlwt = "*"
openpyxl = "*"
pytorch = "*"
torchvision = "*"
scikit-learn = "*"
pcl = "*"
configobj = "*"
pyqtwebkit = "*"
scipy = "*"
traits = "*"
spm12 = "*"
reportlab = "*"
libblitz = "*"
boost-cpp = "*"
dcmtk = "*"
numpy = "<2"
pyyaml = "*"
libminc = "*"
openjpeg = "*"
pywebp = "*"
"sigcpp-2.0" = "*"
gfortran = "*"
graphviz = "*"
doxygen = "*"
pkgconfig = "*"
qwt = "*"
matplotlib = "*"
qtconsole = "*"
ipycanvas = "*"
ipywidgets = "*"
ipyevents = "*"
notebook = "*"
redis-py = "<4.5.0"
redis-server = "<7"
python = "==3.11"
pydantic = "<2"
pyqt = "*"
pyqtwebengine = "*"
ipykernel = "*"
pycryptodome = "*"
pandas = "*"
lark-parser = ">0.7.0"
python-dateutil = "*"
requests = "*"
cryptography = "*"

[dependencies.libjpeg-turbo]
channel = "conda-forge"
version = ">=3.0.0"
