repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: destroyed-symlinks
    # -   id: end-of-file-fixer  # not ready yet
    -   id: fix-byte-order-marker
    -   id: fix-encoding-pragma
    -   id: check-added-large-files
    # -   id: trailing-whitespace  # not ready yet

-   repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        name: flake8 under python3
        language_version: python3
        exclude: ^doc/sphinx/sphinxext/
